export const defaultFormValues = {
  //Client Details
  howToFind: "",
  otherBusinesses: "",
  isPassion: "",
  clientName: "",
  tradingName: "",
  phoneNumber: "",
  email: "",
  businessType: "",
  onboardingfee: "",
  //Accounting
  accountingSection: true,
  salesRange: "",
  salesPrice: 0,
  isCustomSalesPrice: false,
  customSalesPrice: 0,
  //Bookkeeping
  bookkeepingSection: true,
  transactionsPerMonth: "",
  transactionsPrice: 0,
  isCustomBookkeepingPrice: false,
  customBookkeepingPrice: 0,
  //VAT Returns
  VATSection: true,
  range: "",
  rangePrice: 0,
  frequency: "",
  frequencyOffset: 0,
  VATScheme: "",
  totalVATPrice: 0,
  isCustomVATPrice: false,
  customVATPrice: 0,
  //Asset Register
  AssetSection: true,
  fixedAssets: "",
  assetsPrice: 0,
  isCustomAssetPrice: false,
  customAssetPrice: 0,
  //Payroll
  payrollSection: true,
  employeeCount: "",
  payrollPrice: 0,
  payrollFrequency: "",
  employementAllowance: "",
  isCustomPayrollPrice: false,
  customPayrollPrice: null,
  //Pension
  pensionSection: true,
  pensionEmployeeCount: "",
  pensionPrice: 0,
  isCustomPensionPrice: false,
  customPensionPrice: 0,
  //CIS Registration
  CISSection: true,
  contractorsCount: "",
  contractorsPrice: 0,
  reportingFrequency: "",
  offset: 0,
  totalCISPrice: 0,
  isCustomCISPrice: false,
  customCISPrice: "",
  //Multicurrency
  multiCurrencySection: true,
  currencyPrice: 0,
  isCustomCurrencyPrice: false,
  customCurrencyPrice: 0,
  //Custom1
  custom1Section: false,
  custom1Name: "",
  custom1Description: "",
  custom1Price: 0,
  //Custom2
  custom2Section: false,
  custom2Name: "",
  custom2Description: "",
  custom2Price: 0,
  //Addiional Notes

  //Contract
  startDate: "",

  //Risk Scorecard
  industry: "",
  riskScoreData: {},
  riskType: "",

  //INFO related EMAIL
  incorporation: false,
  freeAgent: false,
  virtualAddress: false,
  trustPilot: false,
  pandlePRO: false,
  ecommerceIntegration: false,

  //Data & added by
  contractDate: "",
  addedBy: "Rita",

  //Discount
  isDiscount: false,
  discountValue: "",
  isSpecialDiscount: false,
};

export const industries = [
  "Agriculture",
  "Architecture & Engineering",
  "Automotive",
  "Banking & Financial Services",
  "Construction",
  "Consulting",
  "Consumer Goods",
  "Education",
  "Energy & Utilities",
  "Entertainment & Media",
  "Environmental Services",
  "Fashion & Apparel",
  "Food & Beverage",
  "Government & Public Sector",
  "Healthcare & Medical",
  "Hospitality & Tourism",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Logistics & Transportation",
  "Manufacturing",
  "Marketing & Advertising",
  "Nonprofit & NGOs",
  "Oil & Gas",
  "Pharmaceuticals",
  "Professional Services",
  "Real Estate",
  "Retail & E-commerce",
  "Security Services",
  "Sports & Recreation",
  "Telecommunications",
  "Textile & Garments",
  "Trade & Import/Export",
  "Waste Management",
  "Wholesale & Distribution",
  "Arts & Culture",
  "Mining & Metals",
  "Printing & Publishing",
  "Research & Development",
  "Startups & Entrepreneurship",
  "Technology & Software",
  "Transportation Equipment",
  "Warehousing & Storage",
  "Beauty & Personal Care",
  "Event Management",
  "Human Resources & Staffing",
];
